const AUTHENTICATION_CONSTANTS = Object.freeze({
  SECRET: "VERY_SECRET_CODE",
  SECRET_REFRESH: "VERY_SECRET_REFRESH",
  TOKEN_LIFE: "1d",
  REFRESH_TOKEN_LIFE: 120,
});

module.exports = AUTHENTICATION_CONSTANTS;
