version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: react-nodejs-server
    container_name: react-nodejs-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    networks:
      - mern-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27018:27018"
    networks:
      - mern-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: reactjs-client
    container_name: react-client
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
