version: "3"
services:
  react-client:
    image: react-img
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    build:
      context: ./server
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db #move 'mongo-data' local to '/data/db' image mongo

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
